### DISCUSSION TITLE
APlayer Doesn't Play Audio on My Website

### DISCUSSION THREAD

**Discussion by Alekssandher** [D-Sketon/hugo-theme-reimu#5] [Q&A] [answered]
Hello, I'm trying to play music on my website using the APlayer feature, but it doesn't seem to work as expected. The player appears on the page, but it shows "no audio" and doesn't play anything.
Steps Taken:

## Enabled PJAX in my configuration:

```toml
[params]
  pjax = true
``` 
## Configured the player in params.yml:

```yml
    player:
      aplayer:
        enable: true
        options:
          audio: 
            - name: 'Evangelion Op'
              artist: 'Eva'
              url: 'https://ia600907.us.archive.org/30/items/tvtunes_7772/Neon%20Genesis%20Evangelion.ogg'
              cover: 'images/rei-nerd.webp'
              theme: '#ebd0c2'
          fixed: true
          autoplay: true
          loop: 'all'
          order: 'random'
          preload: 'auto'
          volume: 0.7
          mutex: true
          listFolded: true
```
- Expected Result: The audio should play when the page loads.
- Observed Result: The player shows up, but no audio plays, and it indicates there's no audio available.

## Additional Information:

- The song URL works when accessed directly in the browser: Neon Genesis Evangelion.ogg.
- The images/rei-nerd.webp path is valid and displays correctly on the site.

## Screenshot:

![Captura de tela de 2025-01-17 10-31-06](https://github.com/user-attachments/assets/5a7f3a15-e13a-47a8-8926-9a9e6ecd0fa4)

**Am I missing any configuration steps? What am i doing wrong?**
