### ISSUE TITLE
动态适配主题色

### ISSUE THREAD

**Issue by 2061360308** [D-Sketon/hugo-theme-reimu#22]
## 起因

如下图所示，当文章配置头图后可能会发生这种对比度不足导致文字看不清的问题。希望能够通过js动态提取图片主色进而计算出足够对比度且和图片颜色较为一致字体颜色

![Screenshot_20250314_144541_com_microsoft_emmx_ChromeTabbedActivity_edit_175098609007052.jpg](https://github.com/user-attachments/assets/e3baeeb4-5432-44e8-bc20-1b3feb33f3ff)

## 进阶

我在使用博客主题时按照文档所示调整了对应sass变量列表中的一系列主题颜色。我希望能够增加自动根据博客头图计算主题色的功能，一开始考虑到页面加载性能，最好能够在编译阶段计算完毕。麻烦点是需要引入新的构建工具node或者python，要么就是为linux，Windows等平台各编译一个可执行程序。但是现在由于要给文章头图也适配对应文字颜色，反正都要加载js了不是嘛，二者基本上可以共用一段js。

## 总结

博客主题使用了很多图片，通过引入js算法实现动态适配主题色，文本颜色，能够提供更好的视觉效果。但缺点是在加载页面前需要计算颜色变量拖慢加载速度，而相关js库体积大概15Kb左右，至于自己手搓一个能否进一步压缩还不知道。

**Comment by D-Sketon** [comment]
编译阶段不一定能计算出来吧，如果有用户头图用的随机图床，编译出来的和实际展示的可能不一样

**Comment by 2061360308** [comment]
> 编译阶段不一定能计算出来吧，如果有用户头图用的随机图床，编译出来的和实际展示的可能不一样

确实，没考虑到这种情况。那就客户端算一下。周末我再试试，今天中午写了个试了试，图片主色提取出来基本上刺眼的没法用，找个教程看看怎么调一下

**Comment by 2061360308** [comment]
黑暗模式下颜色还需要调整。。。
其他看起来还不错，但是它必须等到头图加载出来才能切主题色，很明显😅😅😅

Hugo主题真难写，应该说是这个模板语法真难写，代码太乱没法分享

![Image](https://github.com/user-attachments/assets/be93a734-9bbc-4e1b-b59a-ffb6272ab559)
![Image](https://github.com/user-attachments/assets/5dc1cd00-2c76-4c0f-9fda-f1aa9155b882)
![Image](https://github.com/user-attachments/assets/17ecb41a-f21a-4da7-bbea-b7be37c7a0be)
![Image](https://github.com/user-attachments/assets/a29013a6-ceb8-45cd-a045-a6ceec78432a)
![Image](https://github.com/user-attachments/assets/3c24a58c-51fc-4102-b6c8-7dd04a965c20)
![Image](https://github.com/user-attachments/assets/212554cb-f496-4662-812c-3809328da921)
![Image](https://github.com/user-attachments/assets/e8e3730a-497d-4568-9e29-812c3cefaa64)

**Comment by 2061360308** [comment]
## 说明

直接使用了Google开源的[material-color-utilities](https://github.com/material-foundation/material-color-utilities)来处理配色方案，由于这个库自带的那个从图片提取主色调函数的效果不怎么理想，所以我还是使用了 [colorthief ](https://github.com/lokesh/color-thief)来进行提取

> 自带的方法处理过程中，例如：图片由一点蓝色天空，但是视觉感觉整体还是绿色的，但是它会提取成蓝色，类似这样的问题

写了一个动画过渡的效果，后期过渡颜色能够丝滑一些，也不需要在一开始就加载图片了。

## 效果

https://github.com/user-attachments/assets/0a2cacee-af11-41f4-ae7a-5978f5dade12

## 后续集成

![Image](https://github.com/user-attachments/assets/ffb8f935-a597-4c06-8ece-6d3a53ee85c1)

包括两个外部库 [material-color-utilities](https://github.com/material-foundation/material-color-utilities)、[colorthief ](https://github.com/lokesh/color-thief) 都打包进去了，主要是 material-color-utilities 没有提供umd的包，索性一起打包了，另外动画效果的函数也在里面。

ts源码、mjs以及umd包都有，集成到主题的时候，可以使用cdn或者使用ts均可

**Comment by 2061360308** [comment]
@D-Sketon 

这个样子可以了吗😪

https://github.com/2061360308/material-theme.git

**Comment by D-Sketon** [comment]
transition会和loading和pjax冲突，所有添加了个配置https://github.com/2061360308/material-theme/pull/1

**Comment by D-Sketon** [comment]
https://github.com/D-Sketon/hugo-theme-reimu/pull/23 简单实现了该功能，但还未严格测试过

**Comment by 2061360308** [comment]
> [#23](https://github.com/D-Sketon/hugo-theme-reimu/pull/23) 简单实现了该功能，但还未严格测试过

我感觉有一个问题。

我看到你的实现方法里这么绑定
```
[data-theme="dark"]:root body {
      --red-0: var(--red-1);
      --red-4: color-mix(in srgb, var(--md-sys-color-primary) 30%, transparent);
      --red-5: color-mix(in srgb, var(--md-sys-color-primary) 20%, transparent);
      --red-5-5: color-mix(in srgb, var(--md-sys-color-primary) 10%, transparent);
      --red-6: color-mix(in srgb, var(--md-sys-color-primary) 5%, transparent);
      --color-border: var(--red-5);
    }
```
同时你也是这么使用的
```
extractor.applyTheme(scheme, {
    target: document.body,
    dark: document.documentElement.dataset.theme === "dark",
});
```
这可能是我示例的问题，昨天真的是写不动了，所以没写清楚。

方法原型为
```
/**
 * Apply a theme to an element
 *
 * @param theme Theme object
 * @param options Options
 */
export declare function applyTheme(theme: Theme, options?: {
    dark?: boolean;
    target?: HTMLElement;
    brightnessSuffix?: boolean;
    paletteTones?: number[];
}): void;
```

如果是直接在css中就要绑定暗色模式的变量，按照[`material-color-utilities`](https://github.com/material-foundation/material-color-utilities)提供的方法你可以使用`brightnessSuffix`参数，他会将亮色和暗色主题色都输出到css变量并用-light和-dark加以区分。

**Comment by 2061360308** [comment]
```css
body {
      --red-0: var(--md-sys-color-primary);
      --red-1: color-mix(in srgb, var(--md-sys-color-primary) 90%, white);
      --red-2: color-mix(in srgb, var(--md-sys-color-primary) 75%, white);
      --red-3: color-mix(in srgb, var(--md-sys-color-primary) 55%, white);
      --red-4: color-mix(in srgb, var(--md-sys-color-primary) 40%, white);
      --red-5: color-mix(in srgb, var(--md-sys-color-primary) 15%, white);
      --red-5-5: color-mix(in srgb, var(--md-sys-color-primary) 10%, white);
      --red-6: color-mix(in srgb, var(--md-sys-color-primary) 5%, white);
    
      --color-border: var(--red-3);
      --color-link: var(--red-1);
      --color-meta-shadow: var(--red-6);
      --color-h2-after: var(--red-1);
      --color-red-6-shadow: var(--red-2);
      --color-red-3-shadow: var(--red-3);
    }
```
请问，后期会重新梳理整个项目的颜色主题，都改用自动生成的那种样式变量，还是说想这里这种将其简单映射到原来的`--red-0`这种变量呢。

我今天下午也看了下，发现重新配颜色的话工作量有点多。

如果直接映射为原来那个样子的话，我想我可以更改[material-theme](https://github.com/2061360308/material-theme)提供的applyTheme方法，不是将整个配色方案`schemes`应用为css，而是使用简单的`palettes`提供最基础的几个颜色值

从图片中提取的Theme的原型如下：
```ts
/**
 * Theme
 */
export interface Theme {
    source: number;
    schemes: {
        light: Scheme;
        dark: Scheme;
    };
    palettes: {
        primary: TonalPalette;
        secondary: TonalPalette;
        tertiary: TonalPalette;
        neutral: TonalPalette;
        neutralVariant: TonalPalette;
        error: TonalPalette;
    };
    customColors: CustomColorGroup[];
}
```
