### ISSUE TITLE
字体更改

### ISSUE THREAD

**Issue by PantsuMeow** [D-Sketon/hugo-theme-reimu#24]
大佬您好，请问我拥有自定义字体的本地文件，想将其安装到全站字体，该如何操作？
我已经在vendorFont.html找到谷歌api有关的配置，但我试图直接将`<link
  rel="preload"
  as="style"
  href="{{ printf "%s/css?family=%s%s" $fontHost $fontFamilies $fontDisplay }}"
/>`中href完全替换为本地的字体url，字体更改失败。

**Comment by PantsuMeow** [comment]
![Image](https://github.com/user-attachments/assets/6dad5530-69bb-48cc-8458-a5ec02bdbc88)
再附加一个问题，我的所有文章字数统计都由问题，该如何解决？

**Comment by D-Sketon** [comment]
1. 把vendorFont.html改成
```html
<style>
@font-face {
  font-family: "你的字体名称";
      src:url("你的字体地址");
  }
</style>
```
然后params.yaml中
```yaml
# https://fonts.google.com/
# Google Fonts, higher priority than local_font
font:
  article: # 全部注释掉
    # - Mulish
    # - Noto Serif SC
  code:
    # - Ubuntu Mono
    # - Source Code Pro
    # - JetBrains Mono

# Local FallBack Font
local_font:
  article:
    - "你的字体名称"
    - "-apple-system"
    - PingFang SC
    - Microsoft YaHei
    - sans-serif
  code:
    - Menlo
    - Monaco
    - Consolas
    - monospace
```

**Comment by D-Sketon** [comment]
2. hugo.toml里 添加 hasCJKLanguage = true
```toml
[languages.zh-CN]
hasCJKLanguage = true
```
参考 https://gohugo.io/configuration/all/#hascjklanguage
