### ISSUE TITLE
categories 和 tag的设置方法以及相关参数 & 分页设置

### ISSUE THREAD

**Issue by user-xixiboliya** [D-Sketon/hugo-theme-reimu#3]
大佬好，这里有两个疑问，请教：
# 第一个
![image](https://github.com/user-attachments/assets/2f15ffcb-7648-4206-add3-a738d2da6b45)
猜想category的设置是在每一篇post的开头设置的，是这样的吗，例如：
```
---
title: Linux/ubuntu VPN教程
date: 2024-11-14
description: >
draft: false
category:   //是这样的吗
resources:
  - src: "**.{png,jpg}"
    title: "Image #:counter"
    params:
      byline: ""
---
```
还有就是对category和tag设置之后会触发的一些workflow不太清楚，比如博客哪里会出现categories概览这样的。
# params.yml中的分页参数
![image](https://github.com/user-attachments/assets/0c909421-a4c2-41c2-89ca-b35e34ccf96e)
七篇博文都加载到了第一页，请问大佬分页的参数是？
十分感谢！
