### ISSUE TITLE
only_show_capsule_in_index: true 设置不生效

### ISSUE THREAD

**Issue by GuZhengSVT** [D-Sketon/hugo-theme-reimu#47]
Archives每页都有分类和标签。

附部分设置
`params.yml`

```yml
# Archive behavior
only_show_capsule_in_index: true # If you have hugo amounts of tags and categories, you can set this to true to only show the capsule in the index page for better performance

# Experimental, may have a lot of bugs, open with caution!
pjax:
  enable: true

# Experimental
service_worker:
  enable: true
```

`/layouts/_default/taxonomy.html` 未更改
```html
{{ define "main" }}
  <div
    class="archives-outer-wrap"
    data-aos="{{ .Site.Params.animation.options.archive.whole }}"
  >
    {{ if not .Site.Params.only_show_capsule_in_index }}
      {{ partialCached "archives.html" . }}
    {{ end }}
    {{ .Render "list" }}
  </div>
  {{ partial "pagination.html" . }}
{{ end }}
```

`/layouts/partials/archives.html` 未更改
```html
<div class="tag-wrap">
  {{ range .Site.Taxonomies.tags }}
    <div
      class="archives-tag-list-item"
      data-aos="{{ $.Site.Params.animation.options.archive.tag }}"
    >
      <a class="archives-tag-list-link" href="{{ .Page.RelPermalink }}"
        >{{ .Page.Title }}</a
      >
    </div>
  {{ end }}
</div>
<div class="category-wrap">
  {{ range .Site.Taxonomies.categories }}
    <div
      class="archives-category-list-item"
      data-aos="{{ $.Site.Params.animation.options.archive.category }}"
    >
      <a class="archives-category-list-link" href="{{ .Page.RelPermalink }}"
        >{{ .Page.Title }}</a
      >
    </div>
  {{ end }}
</div>
```

如需更多信息，请直接回复。
